/***********************************************************************/
/*                                                                     */
/*  FILE        :stacksct.h                                            */
/*  DATE        :Fri, Jun 12, 2009                                     */
/*  DESCRIPTION :Setting of Stack area                                 */
/*  CPU TYPE    :Other                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.13).    */
/*                                                                     */
/***********************************************************************/
#pragma stacksize su=0x300         /* Do not modify this line. */
#pragma stacksize si=0x100         /* Do not modify this line. */
