/***********************************************************************/
/*                                                                     */
/*  FILE        :typedefine.h                                          */
/*  DATE        :Wed, Aug 27, 2008                                     */
/*  DESCRIPTION :define scalar types.                                  */
/*  CPU GROUP   :118                                                   */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.8).     */
/*                                                                     */
/***********************************************************************/

/*********************************************************
 *  Copyright(c) 2005 Renesas Electronics Corp.
 *  And Renesas Solutions Corp.,All Rights Reserved. 
 * 
 *  typedefine.h
 *  Function: typedef for startup
 *
 *  $Date: 2006/02/13 02:57:05 $
 *  $Revision: 1.1.1.1 $
 *
 *******************************************/
#ifndef __TYPEDEF__
typedef signed char        _SBYTE;
typedef unsigned char      _UBYTE;
typedef signed short       _SWORD;
typedef unsigned short     _UWORD;
typedef signed int         _SINT;
typedef unsigned int       _UINT;
typedef signed long        _SDWORD;
typedef unsigned long      _UDWORD;
typedef signed long long   _SQDWORD;
typedef unsigned long long _UQDWORD;
#endif
#define __TYPEDEF__

