/***********************************************************************/
/*                                                                     */
/*  FILE        :vecttbl.c                                             */
/*  DATE        :Fri, Jun 12, 2009                                     */
/*  DESCRIPTION :Initialize of Vector Table                            */
/*  CPU TYPE    :Other                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.13).    */
/*                                                                     */
/***********************************************************************/
                  


#include "vect.h"

#pragma section C FIXEDVECT

void* const Fixed_Vectors[] = {
//;0xf-fd0  Exception(Supervisor Instruction)
    (void*) Excep_SuperVisorInst,
//;0xf-fd4  Exception(Access)
    (void*) Excep_Access,
//;0xf-fd8  Reserved
    Dummy,
//;0xf-fdc  Exception(Undefined Instruction)
    (void*) Excep_UndefinedInst,
//;0xf-fe0  Reserved
    Dummy,
//;0xf-fe4  Exception(Floating Point)
    (void*) Excep_FloatingPoint,
//;0xf-fe8  Reserved
    Dummy,
//;0xf-fec  Reserved
    Dummy,
//;0xf-ff0  Reserved
    Dummy,
//;0xf-ff4  Reserved
    Dummy,
//;0xf-ff8  NMI
    (void*) NonMaskableInterrupt,
//;0xf-ffc  RESET
//;<<VECTOR DATA START (POWER ON RESET)>>
//;Power On Reset PC
PowerON_Reset_PC                                                                                                                             
//;<<VECTOR DATA END (POWER ON RESET)>>
};
/* eof */
